# Generated by Django 3.0.5 on 2023-10-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20231025_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_activated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
