# Generated by Django 3.0.5 on 2021-06-09 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20210602_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='otc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='otc_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='receive_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='receive_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
