# Generated by Django 3.0.5 on 2021-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20210609_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='otc_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
