# Generated by Django 3.0.5 on 2021-06-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20210609_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
