# Generated by Django 3.0.5 on 2021-06-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_auto_20210609_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_activated',
            field=models.DateTimeField(null=True),
        ),
    ]
