# Generated by Django 3.0.5 on 2021-06-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_user_date_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_activated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
