# Generated by Django 3.0.5 on 2021-06-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20210610_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
