# Generated by Django 3.0.5 on 2021-06-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_dashboard_applied_for_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='applied_for_loan',
            field=models.BooleanField(default=False),
        ),
    ]
