# Generated by Django 3.0.5 on 2021-06-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_dashboard_applied_for_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
