# Generated by Django 3.0.5 on 2023-10-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='available_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
