# Generated by Django 3.0.5 on 2023-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_wallet_available_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='credit_card_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='credit_card_blocked_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
