# Generated by Django 3.0.5 on 2023-10-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_auto_20231025_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='mail_is_sent',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'failed'), ('pending', 'pending'), ('processing', 'Processing'), ('successful', 'successful')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status_message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
