# Generated by Django 3.0.5 on 2021-06-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_transaction_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='iban_number',
        ),
    ]
