# Generated by Django 3.0.5 on 2023-11-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_auto_20231106_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoaccountdetails',
            name='countr',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
