# Generated by Django 3.0.5 on 2021-06-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_auto_20210619_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='credit_card_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
