# Generated by Django 3.0.5 on 2023-11-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_demoaccountdetails_countr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoaccountdetails',
            name='countr',
        ),
    ]
