# Generated by Django 3.0.5 on 2021-06-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_wallet_credit_card_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='credit_card_blocked_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
