# Generated by Django 3.0.5 on 2021-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_auto_20210626_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
