# Generated by Django 3.0.5 on 2022-01-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_transaction_new_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-new_date']},
        ),
    ]
